// AppsForHire — Customer Portal Config
const CUSTOMER = {
  name:          "The Build Company",
  tier:          "starter",
  since:         "March 2026",
  support_email: "info@ghostkitchen.shop",
  stripe_portal: "https://billing.stripe.com/p/login/YOUR_PORTAL_LINK",
  apps: [
    {
      name:        "Ghost Kitchen WebPhone",
      description: "",
      url:         "https://webphone-theghostkitchen-copy.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "SIP Softphone",
      description: "",
      url:         "https://softphone.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Simple 15 30 60",
      description: "",
      url:         "https://simple153060.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Job Tracker + Admin",
      description: "",
      url:         "https://buildco-splitview.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Ghost Book",
      description: "",
      url:         "https://ghostbook-splitview.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Voice Architect",
      description: "",
      url:         "https://voice-architect.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Realtor Radar",
      description: "",
      url:         "https://realtorradar.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "Ark Station",
      description: "",
      url:         "https://arkstation.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    },
    {
      name:        "The Holy Beastiary",
      description: "",
      url:         "https://holybeastiary.appsforhire.app",
      icon:        "📱",
      status:      "active",
      launched:    "March 2026",
    }
  ]
};
